# configurations
# 详情请参考：https://halo.run/develop/theme.html#settings-yaml
sns:
  label: 社交资料
  items:
    nickname_prefix:
      name: nickname_prefix
      label: 昵称前缀
      type: text
      default: '帅哥'
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    twitter:
      name: twitter
      label: Twitter
      type: text
      placeholder: '只需填入 Twitter 用户名即可'
    email:
      name: email
      label: Email
      type: text
      placeholder: '只需填入邮箱地址即可'
    github:
      name: github
      label: Github
      type: text
      placeholder: '只需填入 Github 用户名即可'
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: '只需填入 QQ 号即可'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '只需填入 Telegram Id 即可'
style:
  label: 博客设置
  items:
    hitokoto:
      name: hitokoto
      label: 博客描述开启一言
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    hitokoto_type:
      name: hitokoto_type
      label: 一言句子类型（开启一言后）
      type: select
      default: 'a'
      options:
        - value: ''
          label: '随机'
        - value: 'a'
          label: '动画'
        - value: 'b'
          label: '漫画'
        - value: 'c'
          label: '游戏'
        - value: 'd'
          label: '文学'
        - value: 'e'
          label: '原创'
        - value: 'f'
          label: '来自网络'
        - value: 'g'
          label: '其他'
        - value: 'h'
          label: '影视'
        - value: 'i'
          label: '诗词'
        - value: 'j'
          label: '网易云'
        - value: 'k'
          label: '哲学'
        - value: 'l'
          label: '抖机灵'
    background_picture:
      name: background_picture
      label: body背景图片
      type: attachment
    slogan_text:
      name: slogan_text
      label: slogan
      type: text
      default: ''
      placeholder: '默认为博客标题'
    slogan_text_color:
      name: slogan_text_color
      label: slogan字体颜色
      type: text
      default: '#ff9800'
      placeholder: '请输入颜色码'
      description: '填入颜色，16进制颜色：如#ff9800 或 RGB颜色：如rgb(14,127,0)'
    sitebar_img:
      name: sitebar_img
      label: '侧边栏展示图片'
      type: attachment
    evanyou:
      name: evanyou
      label: evanyou线条
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    blog_ran_time:
      name: blog_ran_time
      label: '站点运行时间统计'
      type: text
      description: '填入起始时间，格式：月/日/年 时:分:秒，如01/01/2020 12:00:00'
    icp:
      name: icp
      label: 'ICP 备案号'
      type: text
      placeholder: '填入 ICP 备案号，没有则不填. '
    custom:
      name: custom
      label: 自定义样式
      type: textarea
      placeholder: '不需要 <style></style> 标签'
plugin:
  label: 插件设置
  items:
    pjax_enabled:
      name: pjax_enabled
      label: 开启 Pjax
      description: '如果开启了背景音乐建议开启 pjax'
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    music_enabled:
      name: music_enabled
      label: 开启背景音乐
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    music_source:
      name: music_source
      label: 音乐播放器播放源
      type: select
      default: netease
      options:
        - value: netease
          label: 网易云音乐
        - value: tencent
          label: QQ音乐
        - value: kugou
          label: 酷狗音乐
        - value: xiami
          label: 虾米音乐
        - value: baidu
          label: 百度音乐
    list_id:
      name: list_id
      label: 音乐播放器歌单ID
      placeholder: '歌单ID'
      description: '播放歌单默认为网易云音乐热歌榜'
      default: '3778678'
      type: text
    sort_by:
      name: sort_by
      label: 歌单排序方式
      default: 'list'
      type: select
      options:
        - value: random
          label: 随机
        - value: list
          label: 顺序
    auto_play:
      name: auto_play
      label: 自动播放
      default: false
      type: radio
      data-type: bool
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_plugin:
      name: sidebar_plugin
      label: 自定义侧边栏插件
      description: '会展示在侧边栏个人信息页的下方'
      type: textarea
      placeholder: '直接粘贴代码'
    sagiri_plugin_js:
      name: sidebar_plugin_js
      label: 自定义侧边栏插件
      description: '会展示在侧边栏个人信息页的下方'
      type: textarea
      placeholder: '直接粘贴代码'
